dist: trusty
sudo: required
language: bash
env:
  global:
  - terraform="0.12.19"
  - terraform_linter="0.13.4"
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
- sudo wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip -O /tmp/packer.zip
- sudo mv /usr/local/bin/packer /usr/local/bin/packer_old && sudo unzip -d /usr/local/bin/ /tmp/packer.zip
- sudo pip install -r ansible/requirements.txt
- sudo pip install ansible-lint
- sudo wget https://releases.hashicorp.com/terraform/${terraform}/terraform_${terraform}_linux_amd64.zip -O /tmp/terraform.zip
- sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
- sudo wget https://github.com/terraform-linters/tflint/releases/download/v${terraform_linter}/tflint_linux_amd64.zip -O /tmp/tflint.zip
- sudo unzip -d /usr/local/bin/ /tmp/tflint.zip
script:
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- cp terraform/prod/terraform.tfvars.example terraform/prod/terraform.tfvars
- cp terraform/stage/terraform.tfvars.example terraform/stage/terraform.tfvars
- terraform get terraform/stage
- tflint --ignore-module=SweetOps/storage-bucket/google;
- terraform get terraform/prod
- tflint --ignore-module=SweetOps/storage-bucket/google;
- ansible-lint;
notifications:
  slack:
    rooms:
      secure: NS83eJdSgWFZWdjxjxeG9BR3cV7epPU6ZBC2dRzLjwmKDZSQQHB8qo/jEVJNBPfXS0WOMqrJ8jhuRzN+vWvTSBk5DlZHdBiz75zcpXHrAuqETGDgR2Fhv7lV0okfxB72HpME7pW4UukGInTgxiV7l5jgxYZM/nuvQcb7CNpNC8+oEXw9DVOhv63XCfU9OL21K05rjXQp3ShQL4i40RuUj4W1WNOpFJ2V4eGODA1wN6FrehyjgFnyIS8Xt2nByDN1PgQC+6oUYtnE613wsMyklHPCF5HLPjDwwBLxmTV1wxYm+7VVDNJ0fBd8/KmnenJeoKzA3kV/NyZiq5yhSHsPGCCqS0+MsGN9SjQfAmlZSSZzwC5RN7pCW+a7wCjZgYzuOI51aZw6Nui8zuNEgvfP/fUBbkHF+Ep/DgLXTdCdcBxuU0i+DHBO/3DMPzojWYQBSPRaXNkIwln/xdpbrTK5fHWJqBdhm9nvO1Ejy7O8qpg2mYbk+XCyyQrhDMByFdPwYNW+GVrfz4rDk8akfG2NNpbpMNbTpPR1uHk6DBHkcg/lYwbqRfkk7VOCIh4Nspwfn/BC+FzMTLqfB1Hrvhq9y6WBLCgJEJqai0ZMvSCbsODbhmXV6Dr+xEWLcggkv5Ic2u7qgFyoajG0f2thIngaUV5fOz2iaNZGYu23ek1uQEc=
